config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers, :except => [:show]

  resources :models, :except => [:show] do
    member do
      get 'pop_model_production_plan'
    end
  end
  
  resources :materials, :except => [:show] do
    collection do
      get 'stock_index' #, :as => :stock
      get 'pop_material_for_text'
      get 'pop_material_for_link'
    end
    member do
      get 'stock'
      put 'collect_print'
    end
  end
  
  resources :washers, :except => [:show] do
    collection do 
      get 'stock_index'
      get 'pop_washer_for_text'
      get 'pop_washer_for_link'
    end
    member do 
      get 'stock'
      put 'collect_print'
    end
  end

  resources :items, :except => [:show, :destroy] do
    member do 
      get 'set_parts'
      put 'set_parts_update'
    end
  end

  resources :process_expenses, :except => [:index, :show, :destroy]

  resources :header_right_check_sheets, :except => [:index, :show, :destroy]

  resources :header_left_check_sheets, :except => [:index, :show, :destroy]

  resources :rolling_right_check_sheets, :except => [:index, :show, :destroy]

  resources :rolling_left_check_sheets, :except => [:index, :show, :destroy]

  resources :process_details, :only => [:multi_new, :multi_edit, :multi_create, :multi_update] do
    collection do
      get 'multi_new'
      get 'multi_edit'
      post 'multi_create'
      put 'multi_update'
    end
  end

  resources :heat_processors, :except => [:show]

  resources :surface_processors, :except => [:show]

  resources :addition_processors, :except => [:show]

  resources :internal_processors, :except => [:show]

  resources :material_suppliers, :except => [:show]

  resources :washer_suppliers, :except => [:show]

  resources :users, :except => [:show] do
    member do
      get 'passwd'
      put 'passwd_update'
    end
  end

  resources :orders, :except => [:show, :new, :create] do
    collection do 
      get 'multi_new'
      post 'multi_create'
      get 'multi_import'
      post 'import'
      post 'multi_import_create'
      get 'fix_parts'
      put 'fix_parts_update'
    end
    member do
      get 'fix_production'
      put 'fix_production_update'
    end
  end

  resources :productions, :except => [:show, :destroy] do
    collection do 
      put 'print_all'
      get 'vote_no_index'
      get 'item_code_index'
      get 'material_index'
      get 'multi_plan'
      put 'multi_plan_update'
      post 'print_t040'
      get 'multi_model'
      put 'multi_model_update'
      get 'yeild_index'
    end
    member do
      post 'report'
      get 'div_branch'
      put 'div_branch_update'
      get 'div_lot'
      put 'div_lot'
      get 'edit_material'
      put 'edit_material_update'
      get 'edit_washer'
      put 'edit_washer_update'
    end
  end

  resources :memos, :only => [:index, :new, :create]

  resources :material_stocks, :except => [:show]
  resources :washer_stocks, :except => [:show]

  resources :material_orders, :except => [:show, :destroy] do
    collection do
      put 'print_all'
      get 'cond_print_t140'
      put 'print_t140'
    end
    member do 
      put 'print_t150'
    end
  end

  resources :washer_orders, :except => [:show, :destroy] do
    collection do 
      put 'print_all'
      get 'cond_print_t141'
      put 'print_t141'
    end
    member do
      put 'collect_print'
    end
  end


  resources :lots, :only => [:index]
  
  resources :process_orders, :only => [:index, :treated_index, :print_all] do
    collection do 
      get 'treated_index'
      put 'print_all'
    end
  end
  
  resources :heat_process_orders, :except => [:show, :destroy, :index]

  resources :surface_process_orders, :except => [:show, :index]

  resources :addition_process_orders, :except => [:show, :index]

  resources :defectives, :except => [:show] do
    collection do
      get 'cond_print'
      put 'print'
    end
  end

  resources :reports, :only => [:index, :download] do
    member do
      get 'download'
    end
  end

  resources :summations, :except => [:show, :destroy] do
    collection do 
      post 'summate_month'
      post 'summate_month_report'
    end
  end

  resources :heat_process_prices, :except => [:show]

  resources :surface_process_prices, :except => [:show]

  resources :notices, :except => [:show]

  resources :calendars, :only => [:index] do
    collection do 
      get 'multi_import'
      post 'multi_import_update'
    end
  end

  #map.top       'top', :controller => :top, :action => :index
  #map.error     'error', :controller => :top, :action => :error

  root :to => 'auth#login', :via => [:get, :post]
  match '/top' => 'top#index', :as => :top, :via => [:get, :post]

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
  get '/error', :to => 'top#error', :as => :error

  get '/auth/logout', :to => 'auth#logout', :as => :logout

  resources :schedule do
    member do
      get 'data'
    end
  end
  resources :gantt do
    member do
      get 'data'
    end
  end
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :user
  
  validates_presence_of     :contents
  
  before_save :prepare_save
  
  private

  def prepare_save
    self.created_ymd = Date.today
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, :only => [:edit, :update, :destroy]

  def index
    notices = Notice.all.order("id desc")
    @notices = notices.paginate(:page => params[:page], :per_page => PAGINATE_PER_PAGE)
  end

  def new
    @notice = Notice.new
    @notice.user = @app.user
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  def create
    begin
      @notice = Notice.new(notice_params)
      @notice.user = @app.user

      if not @notice.valid?
        return render :action => :new
      end

      ActiveRecord::Base::transaction do
        @notice.save!()
      end

      flash[:notice] = t(:success_created, :id => @notice.id)
      redirect_to :action => :edit, :id => @notice.id

    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :new
    end
  end

  # PUT /notices/1
  def update
    begin
      @notice.attributes = notice_params
      if not @notice.valid?
        return render :action => :edit
      end

      ActiveRecord::Base::transaction do
        @notice.save!
      end

      flash[:notice] = t(:success_updated, :id => @notice.id)
      redirect_to :action => :edit

    rescue ActiveRecord::StaleObjectError => so
      flash[:error] = t(:error_stale_object)
      render :action => :edit
    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :edit
    end
  end

  def destroy
    @notice.destroy

    flash[:notice] = t(:success_deleted, :id => @notice.id)
    redirect_to(:action => :index)
  end

  private
    def set_notice
      @notice = Notice.find(params[:id])
    end

    def notice_params
      params.require(:notice).permit(:contents, :lock_version)
    end
end

app/views/notices/_form.html.erb
<div id="main" style="width:800px;">
	<%= raw main_title %>
	<%= raw flash_tag %>

	<%= form_for(@notice) do |f| %>

	<%= @notice.errors.full_messages.join("<br>") %>

	<p><font color="red" style="margin-left:5px;">*</font><%= t(:notice_required) %></p>
	<div class="sheet">
		<h4><%= hlabel_model(get_model_by_controller({})) %></h4>
		<table class="commonSheet">
			<tr>
				<th style="width: 200px;"><%= f.label :user_id %><font class="mark-required" style="margin-left:5px;">*</font></th>
				<td style="width: 200px;"><%= @notice.user.disp_text %></td>
				<th style="width: 200px;"><%= f.label :contents %><font class="mark-required" style="margin-left:5px;">*</font></th>
				<td style="width: 200px;"><%= f.text_field :contents %></td>
			</tr>
		</table>
	</div><!--/ sheet-->

	<%= f.hidden_field :lock_version %>

	<div class="control">
		<%= yield :control %>
	</div><!--/ control-->

	<% end %>
</div><!--/ #main-->

app/views/notices/edit.html.erb
<% content_for :control do %>
    <%= submit_button_tag %>
    <%= cancel_button_tag %>
    <%= delete_image_button_tag @notice %>
<% end %>

<%= render :partial => 'form' %>

app/views/notices/index.html.erb
<div id="main">
	<%= raw main_title %>

	<%= raw flash_tag %>

	<div class="control">
		<%= new_button_tag %>
	</div><!--/ control-->

	<div class="list">
		<div class="paginationCnt"><%= t(:all_count, :scope => :paginate, :cnt => @notices.count) %></div>
		<table class="commonList">
			<thead>
				<tr>
					<th style="width: 100px;"><%= hlabel :notice, :id %></th>
					<th style="width: 100px;"><%= hlabel :notice, :t_created_ymd %>
					<th style="width: 100px;"><%= hlabel :notice, :user_id %></th>
					<th style="width: 500px;"><%= hlabel :notice, :contents %></th>
				</tr>
			</thead>
			<tbody>
				<% @notices.each do |notice| %>
				<tr>
					<td><%= link_to notice.id, edit_notice_path(notice) %></td>
					<td><%= hdate notice.created_ymd %></td>
					<td><%= notice.user.disp_text %></td>
					<td><%= notice.contents %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= will_paginate @notices %>
	</div><!--/ list-->

	<div class="control">
		<%= new_button_tag %>
	</div><!--/ control-->

</div><!--/ #main-->

app/views/notices/new.html.erb
<% content_for :control do %>
    <%= submit_button_tag %>
    <%= cancel_button_tag %>
<% end %>

<%= render :partial => 'form' %>