config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers, :except => [:show]

  resources :models, :except => [:show] do
    member do
      get 'pop_model_production_plan'
    end
  end
  
  resources :materials, :except => [:show] do
    collection do
      get 'stock_index' #, :as => :stock
      get 'pop_material_for_text'
      get 'pop_material_for_link'
    end
    member do
      get 'stock'
      put 'collect_print'
    end
  end
  
  resources :washers, :except => [:show] do
    collection do 
      get 'stock_index'
      get 'pop_washer_for_text'
      get 'pop_washer_for_link'
    end
    member do 
      get 'stock'
      put 'collect_print'
    end
  end

  resources :items, :except => [:show, :destroy] do
    member do 
      get 'set_parts'
      put 'set_parts_update'
    end
  end

  resources :process_expenses, :except => [:index, :show, :destroy]

  resources :header_right_check_sheets, :except => [:index, :show, :destroy]

  resources :header_left_check_sheets, :except => [:index, :show, :destroy]

  resources :rolling_right_check_sheets, :except => [:index, :show, :destroy]

  resources :rolling_left_check_sheets, :except => [:index, :show, :destroy]

  resources :process_details, :only => [:multi_new, :multi_edit, :multi_create, :multi_update] do
    collection do
      get 'multi_new'
      get 'multi_edit'
      post 'multi_create'
      put 'multi_update'
    end
  end

  resources :heat_processors, :except => [:show]

  resources :surface_processors, :except => [:show]

  resources :addition_processors, :except => [:show]

  resources :internal_processors, :except => [:show]

  resources :material_suppliers, :except => [:show]

  resources :washer_suppliers, :except => [:show]

  resources :users, :except => [:show] do
    member do
      get 'passwd'
      put 'passwd_update'
    end
  end

  resources :orders, :except => [:show, :new, :create] do
    collection do 
      get 'multi_new'
      post 'multi_create'
      get 'multi_import'
      post 'import'
      post 'multi_import_create'
      get 'fix_parts'
      put 'fix_parts_update'
    end
    member do
      get 'fix_production'
      put 'fix_production_update'
    end
  end

  resources :productions, :except => [:show, :destroy] do
    collection do 
      put 'print_all'
      get 'vote_no_index'
      get 'item_code_index'
      get 'material_index'
      get 'multi_plan'
      put 'multi_plan_update'
      post 'print_t040'
      get 'multi_model'
      put 'multi_model_update'
      get 'yeild_index'
    end
    member do
      post 'report'
      get 'div_branch'
      put 'div_branch_update'
      get 'div_lot'
      put 'div_lot'
      get 'edit_material'
      put 'edit_material_update'
      get 'edit_washer'
      put 'edit_washer_update'
    end
  end

  resources :memos, :only => [:index, :new, :create]

  resources :material_stocks, :except => [:show]
  resources :washer_stocks, :except => [:show]

  resources :material_orders, :except => [:show, :destroy] do
    collection do
      put 'print_all'
      get 'cond_print_t140'
      put 'print_t140'
    end
    member do 
      put 'print_t150'
    end
  end

  resources :washer_orders, :except => [:show, :destroy] do
    collection do 
      put 'print_all'
      get 'cond_print_t141'
      put 'print_t141'
    end
    member do
      put 'collect_print'
    end
  end


  resources :lots, :only => [:index]
  
  resources :process_orders, :only => [:index, :treated_index, :print_all] do
    collection do 
      get 'treated_index'
      put 'print_all'
    end
  end
  
  resources :heat_process_orders, :except => [:show, :destroy, :index]

  resources :surface_process_orders, :except => [:show, :index]

  resources :addition_process_orders, :except => [:show, :index]

  resources :defectives, :except => [:show] do
    collection do
      get 'cond_print'
      put 'print'
    end
  end

  resources :reports, :only => [:index, :download] do
    member do
      get 'download'
    end
  end

  resources :summations, :except => [:show, :destroy] do
    collection do 
      post 'summate_month'
      post 'summate_month_report'
    end
  end

  resources :heat_process_prices, :except => [:show]

  resources :surface_process_prices, :except => [:show]

  resources :notices, :except => [:show]

  resources :calendars, :only => [:index] do
    collection do 
      get 'multi_import'
      post 'multi_import_update'
    end
  end

  #map.top       'top', :controller => :top, :action => :index
  #map.error     'error', :controller => :top, :action => :error

  root :to => 'auth#login', :via => [:get, :post]
  match '/top' => 'top#index', :as => :top, :via => [:get, :post]

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
  get '/error', :to => 'top#error', :as => :error

  get '/auth/logout', :to => 'auth#logout', :as => :logout

  resources :schedule do
    member do
      get 'data'
    end
  end
  resources :gantt do
    member do
      get 'data'
    end
  end
end

app/models/washer_order.rb
class WasherOrder < ActiveRecord::Base
  belongs_to :washer
  belongs_to :trader
  
  has_many :washer_stocks

  has_and_belongs_to_many :reports
  
  validates_presence_of     :trader_id
  
  validates_presence_of     :order_ymd

  validates_presence_of     :delivery_ymd

  validates_numericality_of :purchase_price, :allow_blank => true
  
  validates_presence_of     :order_quantity
  validates_numericality_of :order_quantity, :allow_blank => true

  validates_presence_of     :delivery_flag
  
  validates_presence_of     :full_delivery_ymd, { :if => Proc.new {|x| x.delivery_flag == FLAG_ON } }

  before_create :set_default
  
  # public class method ========================================================
  def accept_quantities
    washer_stocks.sum(
    :accept_quantity
    )
  end

  # accessor ===================================================================
  attr_accessor :no_in_list
  attr_accessor :select_print
  attr_accessor :price

  # public instance method =====================================================
  def disp_delivery_flag
    disp = I18n.t(:status_delivery_flag_yet)
    disp = I18n.t(:status_delivery_flag_full) if delivery_flag == FLAG_ON
    
    return disp
  end

  def deletable?
    unless washer_stocks.empty?
      errors[:base] << I18n.t(:error_delete_relation)
      return false
    end
    
    return true
  end

  private

  # private instance method ====================================================
  def set_default
    self.print_flag = FLAG_OFF
  end
    
end

app/controllers/washer_orders_controller.rb
class WasherOrdersController < ApplicationController
  before_action :create_options

  before_action :set_washer_order, :only => [:edit, :update, :collect_print]
  
  def index
    cond_trader_id = nil
    cond_trader_id = params[:cond_trader_id].to_i unless params[:cond_trader_id].blank?
    params[:cond_delivery_flag] = FLAG_NON if params[:cond_delivery_flag].blank?
    cond_delivery_flag = params[:cond_delivery_flag].to_i

    @search_cond_date_from_to = SearchCondDateFromTo.new
    @search_cond_date_from_to.set_attributes(params)

    conds = ""
    cond_params = []

    washer_orders = WasherOrder

    conds = "trader_id = IFNULL(?, trader_id)"
    cond_params << cond_trader_id

    if @search_cond_date_from_to.cond_date_from
      conds += " and ? <= delivery_ymd"
      cond_params << @search_cond_date_from_to.cond_date_from
    end
    if @search_cond_date_from_to.cond_date_to.present?
      conds += " and delivery_ymd < ?"
      cond_params << (@search_cond_date_from_to.cond_date_to + 1.days)
    end
    if params[:cond_unprinted]
      washer_orders = washer_orders.includes(:reports).where(reports_washer_orders: { report_id: nil })
    end
    if cond_delivery_flag != FLAG_NON
      conds += " and delivery_flag = ?"
      cond_params << cond_delivery_flag
    end

    washer_orders = washer_orders.where([conds] + cond_params).order("delivery_ymd desc").order(id: :desc)

    session_set_prm

    @washer_orders = washer_orders.paginate(:page => params[:page], :per_page => PAGINATE_PER_PAGE);
    
    @washer_orders.each_with_index{ |washer_order, i|
      washer_order.no_in_list = i
    }
  end

  # 一括発行
  def print_all
    begin
      @washer_orders = []
      @print_all = PrintAll.new

      inputs = params.permit(:washer_order => [:id, :select_print])[:washer_order]
      is_valid = true

      inputs.each {|no, input|
        washer_order = WasherOrder.find(input[:id])
        washer_order.attributes = input
        washer_order.no_in_list = no.to_i
        washer_order.select_print = input[:select_print].to_i

        @washer_orders << washer_order

        next unless washer_order.select_print == FLAG_ON

        result = washer_order.valid?
        is_valid &&= result
        
        @print_all.targets << washer_order
      }

      @washer_orders.sort!{|a, b| a.no_in_list <=> b.no_in_list }

      if not is_valid
        return render :action => :index
      end
      
      cnt = 0
      ActiveRecord::Base::transaction do
        report = AsynchroPrintWasherOrder.prepare_report(@app.user)
        
        @print_all.targets.each{ |washer_order|
          washer_order.reports << report
          washer_order.save!
        }
        
        AsynchroPrintWasherOrder.delay.report(report, @app.user, *@print_all.targets)
#        AsynchroPrintWasherOrder.report(report, @app.user, *@print_all.targets)
      end

      success_id = AsynchroPrintWasherOrder.create_print_message_print_all(@print_all.targets)

      flash[:notice] = t(:success_report_all, :id => success_id)

      redirect_to :action => :index, :params => session[:prm]

    rescue ActiveRecord::StaleObjectError => so
      flash[:error] = t(:error_stale_object)
      render :action => :index
    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :index
    end
  end
  
  # GET /%%controller_name%%/new
  def new
    @washer_order = WasherOrder.new

    @washer = Washer.find(params[:washer_id])
    @washer_order.washer = @washer

    @washer_order.order_ymd = Date.today
    @washer_order.delivery_flag = FLAG_OFF
  end

  # GET /%%controller_name%%/1/edit
  def edit
    @washer = Washer.find(@washer_order.washer_id)

    find_washer_stocks
    notice_force_submit
  end

  # POST /%%controller_name%%
  def create
    begin
      @washer_order = WasherOrder.new(washer_order_params)

      @washer = Washer.find(@washer_order.washer_id)
      @washer_order.washer = @washer

      if not @washer_order.valid?
        return render :action => :new
      end

      ActiveRecord::Base::transaction do
        @washer_order.save!()
      end

      flash[:notice] = t(:success_created, :id => notice_success)
      redirect_to :action => :edit, :id => @washer_order.id

    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :new
    end
  end

  # PUT /%%controller_name%%/1
  def update
    begin
      @washer_order.attributes = washer_order_params
      @washer = Washer.find(@washer_order.washer_id)

      find_washer_stocks

      if params['delete'] #if params['delete.x']
        if not @washer_order.deletable?
          return render :action => :edit
        end

        ActiveRecord::Base::transaction do
          @washer_order.destroy
        end

        flash[:notice] = t(:success_deleted, :id => notice_success)
        redirect_to(:controller => :washers, :action => :stock, :id => @washer.id)
        
      else
        if not @washer_order.valid?
          return render :action => :edit
        end

        ActiveRecord::Base::transaction do
          @washer_order.save!
        end

        return redirect_to new_washer_stock_path(washer_order_id: @washer_order.id) if params['accept']
        
        flash[:notice] = t(:success_updated, :id => notice_success)
      
        redirect_to :action => :edit
      end

    rescue ActiveRecord::StaleObjectError => so
      flash[:error] = t(:error_stale_object)
      render :action => :edit
    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :edit
    end
  end

  # 在庫の回収
  def collect_print
    begin
      @washer = Washer.find(@washer_order.washer_id)
      
      @washer_stocks = []
      @print_all = PrintAll.new

      inputs = params[:washer_stock]
      is_valid = true

      inputs.each {|no, input|
        washer_stock = WasherStock.find(input[:id])
        set_attributes_washer_stock(washer_stock, input, no)

        @washer_stocks << washer_stock

        next unless washer_stock.select_print == FLAG_ON

        result = washer_stock.valid?
        is_valid &&= result
        
        @print_all.targets << washer_stock
      }

      @washer_stocks.sort!{|a, b| a.no_in_list <=> b.no_in_list }

      if not is_valid
        return render :action => :edit
      end

      ActiveRecord::Base::transaction do
        @print_all.targets.each{ |washer_stock|
          washer_stock.collect_flag_on

          washer_stock.save!
        }
      end
      success_message = :success_stock_finish
      
      success_id = @print_all.targets.size.to_s  + I18n.t(:cases_unit)
      
      flash[:notice] = t(success_message, :id => success_id)
      redirect_to :action => :edit, :id => @washer_order.id
      
    rescue ActiveRecord::StaleObjectError => so
      flash[:error] = t(:error_stale_object)
      render :action => :edit
    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :edit
    end
  end


  # 購入履歴発行 get
  def cond_print_t141
    get_all_print_t141
  end
  
  # 購入履歴発行 put
  def print_t141
    begin
      get_all_print_t141

      @purchase_list = PurchaseList.new
      @purchase_list.set_attributes(params)

      @purchase_list.targets = WasherOrder.where(["delivery_flag = ? and ? <= full_delivery_ymd and full_delivery_ymd <= ?", FLAG_ON, @purchase_list.cond_date_from, @purchase_list.cond_date_to])

      if not @purchase_list.valid?
        return render :action => :cond_print_t141
      end
      
      cnt = 0
      ActiveRecord::Base::transaction do
        report = AsynchroPrintWasherPurchaseList.prepare_report_with_term(@app.user, @purchase_list.cond_date_from, @purchase_list.cond_date_to)
        
        AsynchroPrintWasherPurchaseList.delay.report_with_term(report, @app.user, @purchase_list.cond_date_from, @purchase_list.cond_date_to, *@purchase_list.targets)
#        AsynchroPrintWasherPurchaseList.report_with_term(report, @app.user, @purchase_list.cond_date_from, @purchase_list.cond_date_to, *@purchase_list.targets)
      end
      
      success_message = :success_report
      success_id = AsynchroPrintWasherPurchaseList.create_print_message_print_all(@purchase_list.targets)
      
      flash[:notice] = t(success_message, :id => success_id)
      redirect_to :action => :cond_print_t141

    rescue ActiveRecord::StaleObjectError => so
      flash[:error] = t(:error_stale_object)
      render :action => :cond_print_t141
    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :cond_print_t141
    end
  end

  private

  def notice_success(options = {})
    return @washer_order.id
  end

  def create_options
    @washer_suppliers_options = WasherSupplier.all.order(:name)

    @delivery_flag_options = []
    @delivery_flag_options << [I18n.t(:status_delivery_flag_yet), FLAG_OFF]
    @delivery_flag_options << [I18n.t(:status_delivery_flag_full), FLAG_ON]
  end

  def find_washer_stocks
    @washer_stocks = @washer_order.washer_stocks.all.order("id desc")
    
    @washer_stocks.each_with_index{ |washer_stock, i|
      washer_stock.no_in_list = i
      washer_stock.calc_amount!
    }
  end

  def get_all_print_t141
    reports = Report.where(["report_type_id = ?", ReportType.find_by_code(REPORT_TYPE_T141)]).order("id desc")

    session_set_prm

    @reports = reports.paginate(:page => params[:page], :per_page => PAGINATE_PER_PAGE);
  end

  def notice_force_submit
    flash[:alert] = t(:confirm_force_submit, :act => t(:status_arrival)) if @washer_order.delivery_flag == FLAG_ON
  end

  private
    def set_washer_order
      @washer_order = WasherOrder.find(params[:id])
    end

    def washer_order_params
      params.require(:washer_order).permit(:order_ymd, :trader_id, :delivery_ymd, :order_quantity, :reply_delivery_ymd, :delivery_flag, :full_delivery_ymd, :lock_version, :washer_id)
    end
  

app/views/washer_orders/_washer_stocks.html.erb
<% content_for :add_js do %>
function confirm_finish_stock(no_in_list){
	if(!confirm('<%= t(:confirm_stock_finish) %>')){
		return false;
	}

	$("[name='washer_stock[" + no_in_list + "][select_print]']").val(1);

	return confirm_change_tab_core();
}
<% end %>

<% if (@washer_order.new_record? || @washer_stocks.empty?) %>
	<div class="box">
		<h4><%= hlabel(:washer_stock, :t_stock_list) %></h4>
	<%= t(:notice_empty) %>
	</div><!--/ box-->

<% else %>
	
	<%= form_tag(collect_print_washer_order_path(@washer_order), {:method => :put}) do %>

	<%= error_messages_for 'material_stock', :object => @material_stocks %>
	<%= error_messages_for 'print_all' %>
	
	<div class="list" style="width: 1000px;">
		<h4><%= hlabel(:washer_stock, :t_stock_list) %></h4>
		<table class="commonList">
			<thead>
				<tr>
					<th style="width: 60px;"><%= simple_format(t(:t_id, :scope => [:activerecord, :attributes, :washer_stock])) %></th>
					<th style="width: 170px;"><%= simple_format(t(:t_inspection_no, :scope => [:activerecord, :attributes, :washer_stock])) %></th>
					<th style="width: 120px;"><%= hlabel :washer_stock, :accept_ymd %></th>
					<th style="width: 120px;"><%= hlabel :washer_stock, :accept_quantity %></th>
					<th style="width: 120px;"><%= hlabel :washer_stock, :t_excess_amount %></th>
					<th style="width: 120px;"><%= hlabel :washer_stock, :t_stock_price %></th>
					<th colspan="2"><%= hlabel :washer_stock, :t_stock_status %></th>
				</tr>
			</thead>
			<tbody>
				<% @washer_stocks.each do |washer_stock| %>
			        <%= fields_for :washer_stock, washer_stock, :index => washer_stock.no_in_list do |field| %>
					<tr>
						<td>
							<%= link_to(washer_stock.id, edit_washer_stock_url(washer_stock)) %>
							<%= field.hidden_field :id %>
							<%= field.hidden_field :lock_version %>
		      			</td>
						<td><%= washer_stock.inspection_no %></td>
						<td><%= hdate washer_stock.accept_ymd %></td>
						<td class="number"><%= hnumber_with_precision(washer_stock.accept_quantity, :precision => 0) %></td>
						<td class="number"><%= hnumber_with_precision(washer_stock.excess_amount, :precision => 0) %></td>
						<td class="number"><%= hnumber_with_precision(washer_stock.stock_price, :precision => 0) %></td>
						<td style="width: 80px;">
							<%= washer_stock.disp_print_flag %>
							<%= field.hidden_field :select_print %>
						</td>
						<td style="width: 50px;">
<% if washer_stock.collect_flag == FLAG_OFF %>
	<%= submit_button_button_tag(t(:button_stock_finish), :collect_print, :method => :put, :class => "formInBtn", :onClick => "return confirm_finish_stock(" + washer_stock.no_in_list.to_s + ");") %>
<% end %>
						</td>
					</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div><!--/ list-->
	
	<% end %>
<% end %>

app/views/washer_orders/cond_print_t141.html.erb
<% content_for :tabmenu do %>
	<%= tab_menu_for_washer_stock unless (@app.user.role.id == ROLE_ACCOUTING) %>
<% end %> 

<div id="main" style="width: 1000px;">

<%= raw main_title %>

<%= raw flash_tag %>

<p><font color="red" style="margin-left:5px;">*</font><%= t(:notice_required) %></p>

<%= error_messages_for 'purchase_list' %>

<div class="sheet" style="width: 500px;">
	<%= form_tag({:action => :print_t141}, {:method => :put, :name => :print_t141, :id => :print_t141 }) do %>
	<h4><%= t(:search_condition) %></h4>
	<table class="commonSheet">
		<tr>
			<th><%= hlabel(:purchase_list, :t_cond_date) %><font class="mark-required" style="margin-left:5px;">*</font></th>
			<td>
				<%= date_select(:search_cond_date_from_to, :cond_date_from, :object => @purchase_list) %><%= clear_cal_button_tag %>
				<%= t(:search_condition_term) %>
				<%= date_select(:search_cond_date_from_to, :cond_date_to, :object => @purchase_list) %><%= clear_cal_button_tag %>
			</td>
			</td>
			<td class="button"><%= submit_tag(t(:button_report), :confirm => t(:confirm_report)) %></td>
		</tr>
	</table>
	<% end %>

</div><!--/ sheet-->

<div class="list">
	<div class="paginationCnt"><%= t(:all_count, :scope => :paginate, :cnt => @reports.count) %></div>
	<h4><%= hlabel(:summation, :result_list) %></h4>

	<table class="commonList">
		<thead>
			<tr>
				<th><%= raw simple_format(t(:title_id, :scope => [:activerecord, :attributes, :report])) %></th>
				<th><%= raw hlabel :report, :asynchro_status_id %></th>
				<th><%= raw hlabel :report, :title_date %></th>
				<th><%= raw hlabel :report, :user_id %></th>
				<th><%= raw hlabel :material_order, :full_delivery_ymd %></th>
				<th><%= raw hlabel :report, :file_name %></th>
				<th><%= raw simple_format(t(:title_size, :scope => [:activerecord, :attributes, :report])) %></th>
			</tr>
		</thead>
		<tbody>
		<% @reports.each do |report| %>
<%
asynchro_status = AsynchroStatus.new
asynchro_status = report.asynchro_status unless report.asynchro_status.nil?
%>
			<tr>
				<td>
					<%= report.id %>
				</td>
				<td>
					<%= asynchro_status.name %>
				</td>
				<td>
					<%=hdate report.created_at %>
				</td>
				<td>
					<%= report.user.disp_text %>
				</td>
				<td>
					<%= report.note %>
				</td>
				<td>
					<%= link_to report.disp_name, {:controller => :reports, :action => :download, :id => report.id} if asynchro_status.id == ASYNCHRO_STATUS_DONE %>
				</td>
				<td class="number">
					<%= number_to_human_size(report.size) %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>

	<%= will_paginate @reports %>

<!--/ list--></div>

<!--/ #main--></div>

app/views/washer_orders/index.html.erb
<% content_for :tabmenu do %>
	<%= tab_menu_for_washer_stock %>
<% end %> 

<% content_for :control do %>
	<%= submit_button_button_tag(t(:button_report_all), :print_all, :confirm => t(:confirm_report)) %>
<% end %>

<div id="main" style="width: 1080px;">
	<%= raw main_title(:action => :index) %>

	<%= raw flash_tag %>

	<div class="condition" style="width: 900px;">
		<%= form_tag({:action => :index}, {:method => :get, :name => :form_search, :id => :form_search }) do -%>
		<h4><%= t(:search_condition) %></h4>
		<table class="commonCondition">
			<tr>
				<th><%= hlabel :trader, :name %></th>
<%
empty_supplier = WasherSupplier.new
empty_supplier.name = t(:notice_select_all)
washer_supplier_options = [empty_supplier] + @washer_suppliers_options
%>
				<td><%= select_tag(:cond_trader_id, options_from_collection_for_select(washer_supplier_options, :id, :name, params[:cond_trader_id].to_i)) %></td>

				<%= render :partial => "layouts/search_cond_date_from_to", :locals => {:title => hlabel(:washer_order, :delivery_ymd)} %>
<%
cond_delivery_flag_options = []
cond_delivery_flag_options << [t(:notice_select_all), FLAG_NON]
@delivery_flag_options.each{ |opt|
	cond_delivery_flag_options << opt
}
%>
				<th><%= hlabel :washer_order, :delivery_flag %></th>
				<td>
					<%= select_tag(:cond_delivery_flag, options_for_select(cond_delivery_flag_options, params[:cond_delivery_flag].to_i)) %>
				</td>
                                <td><%= check_box_tag :cond_unprinted, true, params[:cond_unprinted] -%>未発行のみ</td>
				<td class="button"> <%= submit_tag t(:search, :scope => :actions) %> </td>


			</tr>
			<tr>

			</tr>
		</table>
		<% end %>
	</div><!--/ condition-->

	<%= form_tag(print_all_washer_orders_path, {:method => :put}) do %>

	<%= error_messages_for 'washer_order', :object => @washer_orders %>
	<%= error_messages_for 'print_all' %>

	<div class="list">
<% if action_name == 'index'%>
		<div class="paginationCnt"><%= t(:all_count, :scope => :paginate, :cnt => @washer_orders.count) %></div>
<% end %>
		<table class="commonList">
			<thead>
				<tr>
					<th><%= raw simple_format(t(:t_washer_order_id, :scope => [:activerecord, :attributes, :washer_order])) %></th>
					<th><%= raw hlabel :washer_order, :order_ymd %></th>
					<th><%= raw hlabel :commons, :washer_name %></th>
					<th><%= raw hlabel :trader, :name %></th>
					<th><%= raw simple_format(t(:t_order_quantity, :scope => [:activerecord, :attributes, :washer_order])) %></th>
					<th><%= raw hlabel :washer_order, :delivery_ymd %></th>
					<th><%= raw hlabel :washer_order, :reply_delivery_ymd %></th>
					<th><%= raw simple_format(t(:t_accedpted_amount, :scope => [:activerecord, :attributes, :washer_order])) %></th>
					<th><%= raw simple_format(t(:t_delivery_flag, :scope => [:activerecord, :attributes, :washer_order])) %></th>
					<th><%= raw hlabel :washer_order, :full_delivery_ymd %></th>
					<th><%= raw simple_format(t(:t_print, :scope => [:activerecord, :attributes, :washer_order])) %></th>
				</tr>
			</thead>
			<tbody>
				<% @washer_orders.each do |washer_order| %>
   			        <%= fields_for :washer_order, washer_order, :index => washer_order.no_in_list do |field| %>
<%
washer = washer_order.washer
washer ||= Washer.new
washer_supplier = washer_order.trader
washer_supplier ||= WasherSupplier.new
report = washer_order.reports.last
report ||= Report.new
attr = prepare_print_all_attr(report)
%>
					<tr>
						<td>
							<%= link_to(washer_order.id, edit_washer_order_url(washer_order)) %>
							<%= field.hidden_field :id %>
	          			</td>
						<td><%= hdate washer_order.order_ymd %></td>
						<td><%= washer.disp_text %></td>
						<td><%= washer_supplier.name %></td>
						<td class="number"><%= hnumber washer_order.order_quantity %></td>
						<td><%= hdate washer_order.delivery_ymd %></td>
						<td><%= hdate washer_order.reply_delivery_ymd %></td>
						<td class="number"><%= hnumber_with_precision(washer_order.accept_quantities, :precision => 0) %></td>
						<td><%= washer_order.disp_delivery_flag %></td>
						<td><%= hdate washer_order.full_delivery_ymd %></td>
						<td><%= field.check_box :select_print, :disabled => attr[:disabled] %><%= attr[:label] %></td>
					</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>

<% if action_name == 'index'%>
		<%= will_paginate @washer_orders %>
<% else %>
                <p><font color="red" style="margin-left:5px;">*</font><%= t(:notice_required) %></p>
                <p style="text-align: center;"><%= t(:notice_paginate_edit) %></p>
<% end %>
<%= hidden_field_tag(:page, params[:page]) %>

	</div><!--/ list-->

	<div class="control">
		<%= yield :control %>
	</div><!--/ control-->
	
	<% end %>
</div><!--/ #main-->