config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers, :except => [:show]

  resources :models, :except => [:show] do
    member do
      get 'pop_model_production_plan'
    end
  end
  
  resources :materials, :except => [:show] do
    collection do
      get 'stock_index' #, :as => :stock
      get 'pop_material_for_text'
      get 'pop_material_for_link'
    end
    member do
      get 'stock'
      put 'collect_print'
    end
  end
  
  resources :washers, :except => [:show] do
    collection do 
      get 'stock_index'
      get 'pop_washer_for_text'
      get 'pop_washer_for_link'
    end
    member do 
      get 'stock'
      put 'collect_print'
    end
  end

  resources :items, :except => [:show, :destroy] do
    member do 
      get 'set_parts'
      put 'set_parts_update'
    end
  end

  resources :process_expenses, :except => [:index, :show, :destroy]

  resources :header_right_check_sheets, :except => [:index, :show, :destroy]

  resources :header_left_check_sheets, :except => [:index, :show, :destroy]

  resources :rolling_right_check_sheets, :except => [:index, :show, :destroy]

  resources :rolling_left_check_sheets, :except => [:index, :show, :destroy]

  resources :process_details, :only => [:multi_new, :multi_edit, :multi_create, :multi_update] do
    collection do
      get 'multi_new'
      get 'multi_edit'
      post 'multi_create'
      put 'multi_update'
    end
  end

  resources :heat_processors, :except => [:show]

  resources :surface_processors, :except => [:show]

  resources :addition_processors, :except => [:show]

  resources :internal_processors, :except => [:show]

  resources :material_suppliers, :except => [:show]

  resources :washer_suppliers, :except => [:show]

  resources :users, :except => [:show] do
    member do
      get 'passwd'
      put 'passwd_update'
    end
  end

  resources :orders, :except => [:show, :new, :create] do
    collection do 
      get 'multi_new'
      post 'multi_create'
      get 'multi_import'
      post 'import'
      post 'multi_import_create'
      get 'fix_parts'
      put 'fix_parts_update'
    end
    member do
      get 'fix_production'
      put 'fix_production_update'
    end
  end

  resources :productions, :except => [:show, :destroy] do
    collection do 
      put 'print_all'
      get 'vote_no_index'
      get 'item_code_index'
      get 'material_index'
      get 'multi_plan'
      put 'multi_plan_update'
      post 'print_t040'
      get 'multi_model'
      put 'multi_model_update'
      get 'yeild_index'
    end
    member do
      post 'report'
      get 'div_branch'
      put 'div_branch_update'
      get 'div_lot'
      put 'div_lot'
      get 'edit_material'
      put 'edit_material_update'
      get 'edit_washer'
      put 'edit_washer_update'
    end
  end

  resources :memos, :only => [:index, :new, :create]

  resources :material_stocks, :except => [:show]
  resources :washer_stocks, :except => [:show]

  resources :material_orders, :except => [:show, :destroy] do
    collection do
      put 'print_all'
      get 'cond_print_t140'
      put 'print_t140'
    end
    member do 
      put 'print_t150'
    end
  end

  resources :washer_orders, :except => [:show, :destroy] do
    collection do 
      put 'print_all'
      get 'cond_print_t141'
      put 'print_t141'
    end
    member do
      put 'collect_print'
    end
  end


  resources :lots, :only => [:index]
  
  resources :process_orders, :only => [:index, :treated_index, :print_all] do
    collection do 
      get 'treated_index'
      put 'print_all'
    end
  end
  
  resources :heat_process_orders, :except => [:show, :destroy, :index]

  resources :surface_process_orders, :except => [:show, :index]

  resources :addition_process_orders, :except => [:show, :index]

  resources :defectives, :except => [:show] do
    collection do
      get 'cond_print'
      put 'print'
    end
  end

  resources :reports, :only => [:index, :download] do
    member do
      get 'download'
    end
  end

  resources :summations, :except => [:show, :destroy] do
    collection do 
      post 'summate_month'
      post 'summate_month_report'
    end
  end

  resources :heat_process_prices, :except => [:show]

  resources :surface_process_prices, :except => [:show]

  resources :notices, :except => [:show]

  resources :calendars, :only => [:index] do
    collection do 
      get 'multi_import'
      post 'multi_import_update'
    end
  end

  #map.top       'top', :controller => :top, :action => :index
  #map.error     'error', :controller => :top, :action => :error

  root :to => 'auth#login', :via => [:get, :post]
  match '/top' => 'top#index', :as => :top, :via => [:get, :post]

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
  get '/error', :to => 'top#error', :as => :error

  get '/auth/logout', :to => 'auth#logout', :as => :logout

  resources :schedule do
    member do
      get 'data'
    end
  end
  resources :gantt do
    member do
      get 'data'
    end
  end
end

app/models/heat_processor.rb
class HeatProcessor < Processor
  def self.available(cond_id, cond_name, cond_address)

    conds = "1 = 1"
    conds_param = []

    if cond_id.present?
      conds += " AND id = ?"
      conds_param << cond_id
    end
    if cond_name.present?
      conds += " AND name LIKE ?"
      conds_param << "%%%s%%" % [sanitize_sql_like(cond_name.strip)]
    end
    if cond_address.present?
      conds += " AND address LIKE ?"
      conds_param << "%%%s%%" % [sanitize_sql_like(cond_address.strip)]
    end

    self.where([conds] + conds_param)
  end
end

app/controllers/heat_processors_controller.rb
class HeatProcessorsController < ApplicationController
  before_action :set_heat_processor, :only => [:edit, :update, :destroy]

  # GET /%%controller_name%%/
  def index
    alls = HeatProcessor.available(params[:cond_id], params[:cond_name], params[:cond_address]).order("id asc")
    
    session_set_prm

    @heat_processors = alls.paginate(:page => params[:page], :per_page => PAGINATE_PER_PAGE);
  end

  # GET /%%controller_name%%/new
  def new
    @heat_processor = HeatProcessor.new
  end

  # GET /%%controller_name%%/1/edit
  def edit
    @heat_processor = Trader.find(params[:id])
  end

  # POST /%%controller_name%%
  def create
    begin
      @heat_processor = HeatProcessor.new
      @heat_processor.attributes = heat_processor_params

      if not @heat_processor.valid?
        return render :action => :new
      end

      ActiveRecord::Base::transaction do
        @heat_processor.save!()
      end

      flash[:notice] = t(:success_created, :id => @heat_processor.disp_text)
      redirect_to :action => :edit, :id => @heat_processor.id

    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :new
    end
  end

  # PUT /%%controller_name%%/1
  def update
    begin
      @heat_processor.attributes = heat_processor_params
      if not @heat_processor.valid?
        return render :action => :edit
      end

      ActiveRecord::Base::transaction do
        @heat_processor.save!
      end

      flash[:notice] = t(:success_updated, :id => @heat_processor.disp_text)
      redirect_to :action => :edit, :id => @heat_processor.id

    rescue ActiveRecord::StaleObjectError => so
      flash[:error] = t(:error_stale_object)
      render :action => :edit
    rescue => e
      flash[:error] = t(:error_default, :message => e.message)
      render :action => :edit
    end
  end

  def destroy
    @heat_processor.destroy

    flash[:notice] = t(:success_deleted, :id => @heat_processor.disp_text)
    redirect_to(:action => :index)
  end
  
  private
    def set_heat_processor
      @heat_processor = HeatProcessor.find(params[:id])
    end
  
    def heat_processor_params
      params.require(:heat_processor).permit(:name, :zip_code, :address, :tel, :fax, :addition_attr1, :lock_version)
    end
end

app/views/heat_processors/_form.html.erb
<div id="main" style="width:800px;">

    <%= raw main_title %>
    <%= raw flash_tag %>

    <%= form_for(@heat_processor) do |f| %>

    <%= @heat_processor.errors.full_messages.join("<br>") %>

    <p><font color="red" style="margin-left:5px;">*</font><%= t(:notice_required) %></p>

    <div class="sheet">
        <h4><%= hlabel_model(get_model_by_controller({})) %></h4>
        <table class="commonSheet">
            <tr>
                <th>
                    <%= hlabel :processor, :id %>
                </th>
                <td>
                    <%= @heat_processor.id %>
                </td>
            </tr>
            <tr>
                <th>
                    <%= hlabel :trader, :name %><font class="mark-required" style="margin-left:5px;">*</font>
                </th>
                <td>
                    <%= f.text_field :name, :size => 25 %>
                </td>
            </tr>
            <tr>
                <th>
                    <%= hlabel :trader, :zip_code %>
                </th>
                <td>
                    <%= f.text_field :zip_code, :size => 25  %>
                </td>
            </tr>
            <tr>
                <th>
                    <%= hlabel :trader, :address %>
                </th>
                <td>
                    <%= f.text_field :address, :size => 50  %>
                </td>
            </tr>
            <tr>
                <th>
                    <%= hlabel :trader, :tel %>
                </th>
                <td>
                    <%= f.text_field :tel, :size => 25  %>
                </td>
            </tr>
            <tr>
                <th>
                    <%= hlabel :trader, :fax %>
                </th>
                <td>
                    <%= f.text_field :fax, :size => 25  %>
                </td>
            </tr>
            <tr>
                <th>
                    <%= hlabel :trader, :addition_attr1 %>
                </th>
                <td>
                    <%= f.text_field :addition_attr1, :size => 25  %>
                </td>
            </tr>
        </table>
    </div><!--/ sheet-->

    <%= f.hidden_field :lock_version %>

    <div class="control">
        <%= yield :control %>
    </div><!--/ control-->

    <% end %>
</div><!--/ #main-->

app/views/heat_processors/edit.html.erb
<% content_for :tabmenu do %>
	<%= tab_menu_for_processor %>
<% end %> 

<% content_for :control do %>
    <%= submit_button_tag %>
    <%= cancel_button_tag %>
    <%= delete_image_button_tag @heat_processor %>
<% end %>

<%= render :partial => 'form' %>

app/views/heat_processors/index.html.erb
<% content_for :tabmenu do %>
	<%= tab_menu_for_processor %>
<% end %> 

<div id="main">
	<%= raw main_title %>

	<%= raw flash_tag %>

	<div class="control">
		<%= new_button_tag %>
	</div><!--/ control-->

	<%= render :partial => 'layouts/traders/search_cond' %>
	
	<div class="list">
		<div class="paginationCnt"><%= t(:all_count, :scope => :paginate, :cnt => @heat_processors.count) %></div>
		<table class="commonList">
			<thead>
				<tr>
					<th><%= hlabel :commons, :id %></th>
					<th><%= hlabel :trader, :name %></th>
					<th><%= hlabel :trader, :address %></th>
				</tr>
			</thead>
			<tbody>
				<% @heat_processors.each do |heat_processor| %>
				<tr>
					<td><%= link_to heat_processor.id, edit_heat_processor_url(heat_processor) %></td>
					<td><%= heat_processor.name %></td>
					<td><%= heat_processor.address %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<%= will_paginate @heat_processors %>

	</div><!--/ list-->

	<div class="control">
		<%= new_button_tag %>
	</div><!--/ control-->
</div><!--/ #main-->

app/views/heat_processors/new.html.erb
<% content_for :tabmenu do %>
	<%= tab_menu_for_processor %>
<% end %> 

<% content_for :control do %>
    <%= submit_button_tag %>
    <%= cancel_button_tag %>
<% end %>

<%= render :partial => 'form' %>